version = 1
[common]
api_mode = false
api_access_token = "password"
default_url = [""]
enable_insert = true
insert_url = [""]
prepend_insert_url = true
enable_filter = false
base_path = "base"
clash_rule_base = "base/all_base.tpl"
surge_rule_base = "base/all_base.tpl"
surfboard_rule_base = "base/all_base.tpl"
mellow_rule_base = "base/all_base.tpl"
quan_rule_base = "base/all_base.tpl"
quanx_rule_base = "base/all_base.tpl"
loon_rule_base = "base/all_base.tpl"
sssub_rule_base = "base/all_base.tpl"
proxy_config = "SYSTEM"
proxy_ruleset = "SYSTEM"
proxy_subscription = "SYSTEM"
append_proxy_type = false

[node_pref]
udp_flag = true
tcp_fast_open_flag = false
skip_cert_verify_flag = true
tls13_flag = false

sort_flag = false

filter_deprecated_nodes = false
append_sub_userinfo = true
clash_use_new_field_name = true

clash_proxies_style = "flow"

[[node_pref.rename_node]]
match = '\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?'
replace = "$1x"

[managed_config]
write_managed_config = true
managed_config_prefix = "http://127.0.0.1:25500"
config_update_interval = 86400
config_update_strict = false
quanx_device_id = ""

[surge_external_proxy]
resolve_hostname = true

[emojis]
add_emoji = false
remove_old_emoji = true

[ruleset]
enabled = true

# Overwrite the existing rules in rule_base
overwrite_original_rules = false

# Perform a ruleset update on request
update_ruleset_on_request = false

[[rulesets]]
import = "base/rulesets.toml"

[[custom_groups]]
import = "base/groups.toml"

[template]
template_path = ""

[[template.globals]]
key = "clash.http_port"
value = "7890"

[[template.globals]]
key = "clash.socks_port"
value = "7891"

[[template.globals]]
key = "clash.redir_port"
value = "7892"

[[template.globals]]
key = "clash.mixed_port"
value = "7893"

[[template.globals]]
key = "clash.allow_lan"
value = "false"

[[template.globals]]
key = "clash.log_level"
value = "info"

[[aliases]]
uri = "/clash"
target = "/sub?target=clash"

[server]
listen = "0.0.0.0"
port = 25500
serve_file_root = "web"

[advanced]
log_level = "info"
print_debug_info = true
max_pending_connections = 10240
max_concurrent_threads = 4
max_allowed_rulesets = 64
max_allowed_rules = 0
max_allowed_download_size = 0
enable_cache = true
cache_subscription = 60
cache_config = 300
cache_ruleset = 21600
script_clean_context = true
async_fetch_ruleset = false
skip_failed_links = true
